name: build tinygo

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      GSCDK_VERSION: 0.5.0
    strategy:
      matrix:
        python-version: [3.9]
        os: ['ubuntu-18.04']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install twine
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Test
        working-directory: .
        run: |
          echo 'hello, world'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/${{ steps.whlfile.outputs.value }}
      - name: Publish a Python distribution to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-18.04' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
